---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cache
  name: cache
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
     app: cache
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cache
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      serviceAccountName: cache
      containers:
      - env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "SERVER_TYPE"
          value: "http"
        - name: "NAME"
          value: "cache"
        - name: "MESSAGE"
          value: "Response from cache"
        - name: "TIMING_VARIANCE"
          value: "1ms"
        - name: "TIMING_50_PERCENTILE"
          value: "15ms"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: nicholasjackson/fake-service:v0.7.1
        imagePullPolicy: IfNotPresent
        name: cache
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          privileged: false
        resources:
          requests:
            memory: "8Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"
